#服务器端容器的配置
server:
  port: 8887

#debug: true

#数据库配置
spring:
  datasource:
    username: root
    password: cai123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FirstDemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

    #JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL得这样写
    properties:
      hibernate:
        format_sql: true